config/routes.rb
LifePhotos::Application.routes.draw do

  namespace :api do
  get "session/create"
  end

  mount Lifephoto::API => "/lifephoto-api"

  post "panda/authorize_upload" , :to => "panda#authorize_upload"

  resources :videos
  get '/calendar' => 'albums#calendar'
  resources :maps ,only: [:index, :new, :create] do end
  get :markers, to: 'maps#markers'

  get "/:provider/login"  => "sessions#new"
  get "/logout" => "sessions#destroy"
  get "/auth/:provider/callback" => "sessions#create" unless Rails.env.development?
  post "/auth/:provider/callback" => "sessions#create" if Rails.env.development?
  get "/auth/failure" => "sessions#failuer"

  namespace :lifephoto do
    get '/calendar' => 'albums#calendar'
    resources :albums do
      member do
        get 'guest_user_show'
      end
    end
    get "/my_list/:user_id" => "albums#my_list" , :defaults => { :format => 'json' }
    resources :photos do
      collection do
        get 'multi_upload'
      end
      resources :comment, only: [:index] do end
    end
    get "/my_photo_list/:user_id" => "photos#my_list" , :defaults => { :format => 'json' }
    resources :groups  do
      collection do
        get 'my_groups', {format: :json }
      end
      resources  :group_member, to: 'groups/group_member' do
        collection do
          get 'invite_member'
          post 'invite'
        end
      end
    end
    get "/groups/:group_id/join_this_group"  =>  "groups/group_member#join_this_group"
    resources :events do
      collection do
        get 'event_list', {format: :json }
      end
    end
    get "/my_events_pdf" => "events#to_pdf",  :defaults => { format: 'pdf' }
  end

  namespace :api ,  defaults: { format: 'json' }do
    resources :photos do

    end
    resources :albums do

    end
  end
  

  root 'lifephoto/top#index'

end

app/views/common/_album_menu.html.haml
%menu
  = link_to_unless_current 'アルバム一覧', lifephoto_albums_path
  \&nbsp;&nbsp;|&nbsp;&nbsp;
  \#{link_to_unless_current 'アルバム作成', new_lifephoto_album_path,  "data-no-turbolink" => true}&nbsp;&nbsp;|&nbsp;&nbsp;
  \#{link_to_unless_current 'カレンダーから見るアルバム', calendar_path,  "data-no-turbolink" => true}&nbsp;&nbsp;|&nbsp;&nbsp;
  \#{link_to_unless_current '地図から見るアルバム', maps_path, "data-no-turbolink" => true}&nbsp;&nbsp;|&nbsp;&nbsp;
%br/

app/views/common/_group_menu.html.haml
%menu
  = link_to_unless_current 'グループ作成', new_lifephoto_group_path, "data-no-turbolink" => true
  \&nbsp;&nbsp;|&nbsp;&nbsp;
  \#{link_to_unless_current 'マイグループ一覧', lifephoto_groups_path}&nbsp;&nbsp;|&nbsp;&nbsp;
%br/

app/views/common/_menu.html.haml
%menu
  = link_to_unless_current 'トップページへ', root_path
  \&nbsp;&nbsp;|&nbsp;&nbsp;
  \#{link_to_unless_current 'Myアルバム', lifephoto_albums_path}&nbsp;&nbsp;|&nbsp;&nbsp;
  \#{link_to_unless_current 'My写真', lifephoto_photos_path}&nbsp;&nbsp;|&nbsp;&nbsp;
  \#{link_to_unless_current 'Myグループ', lifephoto_groups_path}&nbsp;&nbsp;|&nbsp;&nbsp;
  \#{link_to_unless_current '日記をつける', lifephoto_events_path, "data-no-turbolink" => true}&nbsp;&nbsp;|&nbsp;&nbsp;

app/views/common/_photo_menu.html.haml
%menu
  = link_to_unless_current '写真投稿', new_lifephoto_photo_path
  \&nbsp;&nbsp;|&nbsp;&nbsp;
  \#{link_to_unless_current '複数写真一括投稿', multi_upload_lifephoto_photos_path}&nbsp;&nbsp;|&nbsp;&nbsp;
%br/